-- Drop script for all tables with CASCADE option

-- Drop tables with CASCADE option
DROP TABLE  F23_S001_T6_PaymentDetails CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_MonthlyTripRecord CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_RideDetails CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_CouponDetails CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_DriverIdentification CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_Vehicle CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_NonStudent CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_Student CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_CustomerPhoneNumber CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_Customer CASCADE CONSTRAINTS PURGE;
DROP TABLE  F23_S001_T6_Driver CASCADE CONSTRAINTS PURGE;